apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: store-mq
  namespace: rt-inventory-dev
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  queueManager:
    name: QM1
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    metrics:
      enabled: true
    route:
      enabled: true
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.4.0-r1
  web:
    enabled: true

