apiVersion: v1
kind: ConfigMap
metadata:
  name: store-inventory-cm
data:
  APP_VERSION: 0.0.10
  STORE_INVENTORY_TOPIC: store.inventory
  ITEM_TOPIC: items
  KAFKA_APPLICATION_ID: eda-store-aggregator
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-bootstrap.rt-inventory-dev.svc:9092
  QUARKUS_KAFKA_STREAMS_TOPICS: items,store.inventory
  QUARKUS_KAFKA_HEALTH_ENABLED: "false"
  QUARKUS_KAFKA_STREAMS_HEALTH_ENABLED: "false"
  QUARKUS_KAFKA_CONNECTOR_HEALTH_ENABLED: "false"
  