apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-quarkus-app
spec:
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: revision
    type: string
    description: The git tag to clone.
  - name: DOCKERFILE
    type: string
    default: src/main/docker/Dockerfile.jvm
  - name: image-server
    default: quay.io
  - name: image-namespace
    default: ibmcase
  - name: image-repository
    default: ""
  - name: image-tag
    default: ""
  - name: GOALS
    type: string
    default: -DskipTests, clean, package
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
      - name: output
        workspace: shared-workspace
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
    - name: build-quarkus-app
      taskRef:
        name: maven
      runAfter:
        - fetch-source
      params:
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      taskRef:
        name: build-dr-image
        kind: Task
      runAfter:
        - build-quarkus-app
      params:
        - name: image-server
          value: $(params.image-server)
        - name: image-namespace
          value: $(params.image-namespace)
        - name: image-repository
          value: $(params.image-repository)
        - name: image-tag
          value: $(params.image-tag)
        # since pushing to internal registry we skip TLS verify
        - name: TLSVERIFY
          value: 'false'
        - name: DOCKERFILE
          value: '$(params.DOCKERFILE)'
      workspaces:
        - name: source
          workspace: shared-workspace