version: '3.7'
services:
  elastic:
    image: elasticsearch:8.0.1
    hostname: elastic
    container_name: elastic
    environment:
    - discovery.type=single-node
    - cluster.name=rt-cluster
    - node.name=elastic
    - xpack.security.enabled=false
    - bootstrap.memory_lock=true
    - network.host=0.0.0.0
    - ELASTICSEARCH_PASSWORD=passw0rd
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    container_name: kibana
    depends_on: 
    - elastic
    ports:
    - 5601:5601
    environment:
    - ELASTICSEARCH_HOSTS=http://elastic:9200
    - XPACK_SECUTITY_ENABLED=false
