apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: item-inventory
  namespace: rt-inventory-dev
  labels:
    strimzi.io/cluster: dev
spec:
  partitions: 1
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: items
  namespace: rt-inventory-dev
  labels:
    strimzi.io/cluster: dev
spec:
  partitions: 1
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: store-inventory
  namespace: rt-inventory-dev
  labels:
    strimzi.io/cluster: dev
spec:
  partitions: 1
  replicas: 3