namespace: rt-inventory-dev
#bases:
#  - github.com/jbcodeforce/eda-gitops-catalog/kafka-strimzi/operator/overlay/stable?ref=main
resources:
# Do we need to intall operator?
  - kafka-cluster.yaml
  - kafka-users.yaml
  - kafka-topics.yaml