apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: eda-registry
spec:
  configuration:
    persistence: kafkasql
    kafkasql:
      bootstrapServers: es-demo-kafka-bootstrap:9092
      