apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prod-kafka
  namespace: rt-inventory-staging
spec:
  podMetricsEndpoints:
  - port: tcp-prometheus
    scheme: http
  selector:
    matchLabels:
      eventstreams.ibm.com/cluster: prod
      eventstreams.ibm.com/kind: Kafka
      eventstreams.ibm.com/name: prod-kafka

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prod-metrics
  namespace: rt-inventory-staging
spec:
  podMetricsEndpoints:
  - port: metrics
    scheme: http
  selector:
    matchLabels:
      eventstreams.ibm.com/name: prod-kafka