apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: es-demo-day2
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      serviceAccountName:  rt-inv-job-sa
      containers:
      - name: copysecret
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl get secret ibm-entitlement-key -n cp4i-eventstreams -o json | jq -r '.metadata.namespace=\"es-demo-day2\"' | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.creationTimestamp, .metadata.ownerReferences)' | kubectl apply -f -"
      restartPolicy: Never 