apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: demo
  namespace: es-demo-day2
spec:
  version: 10.5.0
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  requestIbmServices:
    iam: false
    monitoring: false
  adminApi: {}
  adminUI: {}
  security:
    internalTls: TLSv1.2
  strimziOverrides:
    entityOperator: 
      topicOperator: {}
      userOperator: {}
    kafka:
      replicas: 1
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '2.8'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.cleaner.threads: 6
        log.message.format.version: '2.8'
        num.io.threads: 6
        num.network.threads: 6
      listeners:
        plain: {}
      storage:
        type: ephemeral
    zookeeper:
      replicas: 1
      storage:
        type: ephemeral
