apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic
  labels:
    eventstreams.ibm.com/cluster: demo
spec:
  partitions: 1 
  replicas: 1
  config:
    min.insync.replicas: 1
    cleanup.policy: delete
    retention.ms: 604800000
    segment.ms: 604800000
    file.delete.delay.ms: 60000
    max.message.bytes: 1048588
    message.timestamp.type: LogAppendTime

