apiVersion: batch/v1
kind: Job
metadata:
  name: cp-cacert-secret
  namespace: rt-inventory-dev
spec:
  template:
    metadata:
      name: cp-cacert-secret
    spec:
      serviceAccountName:  rt-inv-job-sa
      containers:
      - name: copysecret
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "if [ -z '$(kubectl get secret es-demo-cluster-ca-cert -n rt-inventory-dev | grep found)' ]; \
          then kubectl get secret es-demo-cluster-ca-cert -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"rt-inventory-dev\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.creationTimestamp)'  \
          | kubectl apply -n rt-inventory-dev -f - ;\
          else echo already_created; fi"
      restartPolicy: Never 