apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: rt-demo.items
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 3 
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 7200000
    segment.bytes: 1073741824


---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: item-aggregator-itemstock-repartition
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster: es-demo
spec:
  partitions: 3 
  replicas: 3
---

apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: rt-demo.item.inventory
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster:  es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 7200000
    segment.bytes: 1073741824


---

apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: rt-demo.store.inventory
  namespace: cp4i
  labels:
    eventstreams.ibm.com/cluster:  es-demo
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 7200000
    segment.bytes: 1073741824
