apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_VERSION: 0.0.10
  APP_TARGET_MESSAGING: kafka,IBMMQ
  KAFKA_BOOTSTRAP_SERVERS: lab-kafka-bootstrap.rt-inventory-lab.svc:9092
  KAFKA_TOPIC_NAME: items
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  USER_CERT_PWD: none
  MQ_HOST: store-mq-ibm-mq.rt-inventory-lab.svc
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: ITEMS
  MQ_CHANNEL: DEV.APP.SVRCONN