apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: rt-inventory-mq-services
  namespace: openshift-gitops
spec:
  destination:
    namespace: std-1-rt-inventory
    server: https://kubernetes.default.svc
  project: student-1
  source:
    path: environments/multi-tenancy/student/services/ibm-mq/overlays
    repoURL: https://github.com/ibm-cloud-architecture/eda-rt-inventory-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
