apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: rt-inventory-staging
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      serviceAccountName:  rt-inv-job-sa
      containers:
      - name: copysecret
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "if [ -z \"$(kubectl get secret ibm-entitlement-key -n rt-inventory-staging | grep found)\" ]; \
          then kubectl get secret ibm-entitlement-key -n rt-inventory-dev -o json \
          | jq -r '.metadata.namespace=\"rt-inventory-staging\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences, .metadata.resourceVersion,  .metadata.creationTimestamp)'  \
          | kubectl apply -f - ;\
          else echo already_created; fi"
      restartPolicy: Never 