apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: demo-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: es-demo-day2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo/env
    repoURL: https://github.com/ibm-cloud-architecture/eda-rt-inventory-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
