apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-refarch-eda-store-simulator
  name: rt-inventory-dev-app-refarch-eda-store-simulator
  namespace: openshift-gitops
spec:
  destination:
    namespace: rt-inventory-dev
    server: https://kubernetes.default.svc
  project: rt-inventory
  source:
    path: environments/rt-inventory-dev/apps/app-refarch-eda-store-simulator/overlays
    repoURL: https://github.com/jbcodeforce/rt-inventory-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
