apiVersion: batch/v1
kind: Job
metadata:
  name: cp-ca-secret
  namespace: std-1-rt-inventory
spec:
  template:
    metadata:
      name: cp-ca-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - kubectl get secret es-demo-cluster-ca-cert -n cp4i-eventstreams -o json | jq -r '.metadata.namespace="std-1-rt-inventory"' | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.creationTimestamp, .metadata.ownerReferences)' | kubectl apply -n std-1-rt-inventory -f -
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
