apiVersion: v1
kind: ConfigMap
metadata:
  name: item-inventory-cm
data:
  APP_VERSION: 0.0.10
  APP_ITEM_INVENTORY_TOPIC: rt-item.inventory
  APP_ITEMS_TOPIC: rt-items
  KAFKA_APPLICATION_ID: eda-item-aggregator
  KAFKA_SECURITY_PROTOCOL: SSL
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-bootstrap.rt-inventory-dev.svc:9093
