apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: cp4i
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      serviceAccountName:  cp4i-job-sa
      containers:
      - name: copysecret
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
        - "if [ -z '$(kubectl get secret ibm-entitlement-key | grep found)' ]; \
          then kubectl get secret ibm-entitlement-key -n openshift-operators -o json \
          | jq -r '.metadata.namespace=\"cp4i\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink, .metadata.creationTimestamp)'  \
          | kubectl apply -f - ;\
          else echo already_created; fi"
      restartPolicy: Never 