apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: std-1-rt-inventory
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - kubectl get secret ibm-entitlement-key -n cp4i-eventstreams -o json |
          jq -r '.metadata.namespace="std-1-rt-inventory"' | kubectl apply -f -
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
