apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_VERSION: 0.0.10
  APP_TARGET_MESSAGING: kafka,IBMMQ
  KAFKA_BOOTSTRAP_SERVERS: es-demo-kafka-bootstrap.cp4i.svc:9092
  KAFKA_TOPIC_NAME: rt-demo.items
  KAFKA_SECURITY_PROTOCOL: PLAINTEXT
  USER_CERT_PWD: none
  KAFKA_CERT_PWD: ""
  MQ_HOST: store-mq-ibm-mq.rt-inventory-dev.svc
  # external: mq1-cp4i-ibm-mq-qm-cp4i-mq1.apps.biggs.coc-ibm.com
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: ITEMS
  MQ_CHANNEL: DEV.APP.SVRCONN
  #SASL_MECHANISM: SSL